# Generated by Django 3.2.2 on 2021-06-15 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('autorite', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('id_candidat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidat.candidat')),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libellé', models.CharField(max_length=100)),
                ('Type', models.CharField(default='programation', max_length=250)),
                ('Niveau', models.CharField(default='True', max_length=100, null=True)),
                ('Description', models.TextField(blank=True)),
                ('id_candidat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidat.candidat')),
            ],
        ),
        migrations.CreateModel(
            name='Réfférence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Numero', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100, null=True)),
                ('ContactProffessionnel', models.CharField(max_length=100)),
                ('Entreprise', models.CharField(max_length=100)),
                ('descriptions', models.CharField(max_length=100)),
                ('id_candidat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidat.candidat')),
            ],
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Niveau', models.CharField(max_length=100)),
                ('id_candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidat.candidat')),
            ],
        ),
        migrations.CreateModel(
            name='Interet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitulé', models.CharField(max_length=100)),
                ('id_Personne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidat.candidat')),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Niveau', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=100)),
                ('contexte', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('DateDebut', models.DateField(null=True)),
                ('DateFin', models.DateField(null=True)),
                ('id_candidat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidat.candidat')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomEntreprise', models.CharField(max_length=100)),
                ('PosteOccuppet', models.CharField(max_length=100)),
                ('contexte', models.CharField(max_length=250)),
                ('resume', models.CharField(max_length=250)),
                ('dateDebut', models.DateField(max_length=250)),
                ('dateFin', models.DateField(max_length=250)),
                ('id_candidat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidat.candidat')),
            ],
        ),
        migrations.CreateModel(
            name='DeclarationPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField()),
                ('id_candidat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidat.candidat')),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Certifications', models.ManyToManyField(to='sections.Certification')),
                ('Competence', models.ManyToManyField(to='sections.Competence')),
                ('Declaration', models.ManyToManyField(to='sections.DeclarationPerson')),
                ('Experiences', models.ManyToManyField(to='sections.Experience')),
                ('Formations', models.ManyToManyField(to='sections.Formation')),
                ('Langues', models.ManyToManyField(to='sections.Langue')),
                ('Refferances', models.ManyToManyField(to='sections.Réfférence')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidat.candidat')),
                ('interet', models.ManyToManyField(to='sections.Interet')),
            ],
        ),
    ]
