# Generated by Django 3.2.2 on 2021-06-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='Refferances',
            field=models.ManyToManyField(null=True, to='sections.Réfférence'),
        ),
    ]
