# Generated by Django 3.2.2 on 2021-06-17 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_alter_cv_refferances'),
    ]

    operations = [
        migrations.AddField(
            model_name='declarationperson',
            name='titre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='cv',
            name='Declaration',
        ),
        migrations.AddField(
            model_name='cv',
            name='Declaration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sections.declarationperson'),
        ),
    ]
