# Generated by Django 3.2.2 on 2021-06-18 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_auto_20210617_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='Declaration',
        ),
        migrations.AddField(
            model_name='cv',
            name='Declaration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sections.declarationperson'),
        ),
    ]
