# Generated by Django 3.2.2 on 2021-06-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0005_auto_20210618_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='Certifications',
            field=models.ManyToManyField(blank=True, to='sections.Certification'),
        ),
    ]
