# Generated by Django 3.2.2 on 2021-06-19 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0006_alter_cv_certifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='Declaration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='declaration', to='sections.declarationperson'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='Experiences',
            field=models.ManyToManyField(blank=True, null=True, related_name='experiences', to='sections.Experience'),
        ),
    ]
