# Generated by Django 3.2.2 on 2021-06-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0008_auto_20210619_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='langue',
            name='Nom',
            field=models.CharField(choices=[('Debutant', 'Debutant'), ('Intermédiaire', 'Intermédiaire'), ('Bien', 'Bien'), ('Très bien', 'Très bien'), ('Excellent', 'Excellent')], max_length=100),
        ),
    ]
