# Generated by Django 3.2.2 on 2021-06-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0009_alter_langue_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='Niveau',
            field=models.CharField(choices=[('Debutant', 'Debutant'), ('Intermédiaire', 'Intermédiaire'), ('Bien', 'Bien'), ('Très bien', 'Très bien'), ('Excellent', 'Excellent')], max_length=100, null=True),
        ),
    ]
