# Generated by Django 3.2.2 on 2021-06-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0010_alter_competence_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='langue',
            name='Niveau',
            field=models.CharField(choices=[('Debutant', 'Debutant'), ('Intermédiaire', 'Intermédiaire'), ('Bien', 'Bien'), ('Très bien', 'Très bien'), ('Excellent', 'Excellent')], max_length=100),
        ),
        migrations.AlterField(
            model_name='langue',
            name='Nom',
            field=models.CharField(max_length=100),
        ),
    ]
