# Generated by Django 3.2.2 on 2021-06-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0011_auto_20210619_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='institution',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='langue',
            name='Niveau',
            field=models.CharField(choices=[('', '---selectionner votre niveau---'), ('Debutant', 'Debutant'), ('Intermédiaire', 'Intermédiaire'), ('Bien', 'Bien'), ('Très bien', 'Très bien'), ('Excellent', 'Excellent')], max_length=100),
        ),
    ]
