# Generated by Django 3.2.2 on 2021-06-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0012_auto_20210620_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='Niveau',
            field=models.CharField(choices=[('width:20', 'Debutant'), ('width:40%', 'Intermédiaire'), ('width:60%', 'Bien'), ('width:80%', 'Très bien'), ('width:100%', 'Excellent')], max_length=100, null=True),
        ),
    ]
