# Generated by Django 3.2.2 on 2021-06-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0013_alter_competence_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='Niveau',
            field=models.CharField(choices=[('20', 'Debutant'), ('40%', 'Intermédiaire'), ('60%', 'Bien'), ('80%', 'Très bien'), ('100%', 'Excellent')], max_length=100, null=True),
        ),
    ]
