# Generated by Django 3.2.2 on 2021-06-15 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('dateNaissance', models.DateField()),
                ('lieuNaissance', models.CharField(max_length=100, null=True)),
                ('Nationalite', models.CharField(max_length=100, null=True)),
                ('Addresse', models.CharField(max_length=100, null=True)),
                ('Image', models.ImageField(null=True, upload_to='')),
                ('Telephone', models.CharField(max_length=100, null=True)),
                ('sexe', models.CharField(choices=[('FEMELLE', 'FEMELLE'), ('MALE', 'MALE')], max_length=120, null=True)),
                ('site', models.CharField(max_length=100, null=True)),
                ('linkedin', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
    ]
