# Generated by Django 3.2.2 on 2021-06-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidat', '0002_alter_candidat_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='dateNaissance',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='prenom',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
