# Generated by Django 3.2.2 on 2021-06-16 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('candidat', '0004_alter_candidat_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('prenom', models.CharField(max_length=100, null=True)),
                ('nom', models.CharField(max_length=100, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Image', models.ImageField(null=True, upload_to='media')),
                ('util', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
    ]
